/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomMenu: typeof import('./src/components/screen/BottomMenu.vue')['default']
    HomePanelContent: typeof import('./src/components/dashboard/HomePanelContent.vue')['default']
    LayerControl: typeof import('./src/components/map/LayerControl.vue')['default']
    MapCompass: typeof import('./src/components/map/MapCompass.vue')['default']
    MapMeasureControl: typeof import('./src/components/map/MapMeasureControl.vue')['default']
    MapPopupTitle: typeof import('./src/components/map/MapPopupTitle.vue')['default']
    MapToolMenu: typeof import('./src/components/map/MapToolMenu.vue')['default']
    MapToolPanel: typeof import('./src/components/map/MapToolPanel.vue')['default']
    MapToolsPanel: typeof import('./src/components/map/MapToolsPanel.vue')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    MetricCard: typeof import('./src/components/screen/MetricCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    OperationWarningContext: typeof import('./src/components/dashboard/OperationWarningContext.vue')['default']
    OperationWarningDetail: typeof import('./src/components/dashboard/OperationWarningDetail.vue')['default']
    OperationWarningQuery: typeof import('./src/components/dashboard/OperationWarningQuery.vue')['default']
    PanelSection: typeof import('./src/components/screen/PanelSection.vue')['default']
    ResourceLayerPanel: typeof import('./src/components/map/ResourceLayerPanel.vue')['default']
    ResourceSearchPanel: typeof import('./src/components/map/ResourceSearchPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenHeader: typeof import('./src/components/screen/ScreenHeader.vue')['default']
    SidePanel: typeof import('./src/components/screen/SidePanel.vue')['default']
    SituationLeftContent: typeof import('./src/components/dashboard/SituationLeftContent.vue')['default']
    SituationRightContent: typeof import('./src/components/dashboard/SituationRightContent.vue')['default']
    TechModalFrame: typeof import('./src/components/screen/TechModalFrame.vue')['default']
    WarningRadarLayer: typeof import('./src/components/map/WarningRadarLayer.vue')['default']
  }
}
